const KEY='mouth-mover-v1';
const DEFAULT_BACKEND='https://mouth-mover-ai.stedford30.workers.dev';
const defaultCharacters=[
{id:'nova',name:'Nova',tagline:'Your chaotic space-explorer friend.',category:'Adventure',avatar:'',personality:'Cheerful, curious, brave, playful and a little chaotic.',backstory:'Nova is a young space explorer who maps strange planets and collects stories from everyone she meets.',style:'Energetic, friendly messages with occasional jokes and emojis.',voice:'default',greeting:'Hey! 🚀 You made it! Want to explore somewhere weird with me?'},
{id:'sage',name:'Sage',tagline:'A patient AI study buddy.',category:'Study',avatar:'',personality:'Patient, encouraging, clever and honest. Never does schoolwork dishonestly.',backstory:'Sage was designed as a study companion who loves turning confusing subjects into simple explanations.',style:'Clear, supportive, concise, with examples and small quizzes.',voice:'default',greeting:'Hi! What are we learning today? I can explain it step by step.'},
{id:'pixel',name:'Pixel',tagline:'A gamer who never stops talking.',category:'Gaming',avatar:'',personality:'Competitive, funny, enthusiastic and loyal.',backstory:'Pixel lives for games, speedruns, strange glitches and co-op adventures.',style:'Fast, casual, gamer slang, but still understandable.',voice:'default',greeting:'Yo! 🎮 Ready up. What are we playing—or are we making our own game?'}
];
let state=loadState();
let activeId=null, activeCategory='All';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');return Object.assign({characters:defaultCharacters,chats:{},settings:{apiUrl:DEFAULT_BACKEND,demo:false}},saved,{settings:Object.assign({apiUrl:DEFAULT_BACKEND,demo:false},saved.settings||{})})}catch{return {characters:defaultCharacters,chats:{},settings:{apiUrl:DEFAULT_BACKEND,demo:false}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function initials(name){return (name||'?').trim().split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function portrait(c,small=false){return `<div class="portrait ${small?'small':''}">${c.avatar?`<img src="${escapeHtml(c.avatar)}" alt="${escapeHtml(c.name)}">`:`<div class="avatar-fallback">${escapeHtml(initials(c.name))}</div>`}</div>`}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}-view`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo(0,0)}
function renderCategories(){const cats=['All',...new Set(state.characters.map(c=>c.category))];$('#category-chips').innerHTML=cats.map(x=>`<button class="chip ${x===activeCategory?'active':''}" data-category="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('')}
function renderCharacters(){renderCategories();const q=($('#character-search')?.value||'').toLowerCase();const list=state.characters.filter(c=>(activeCategory==='All'||c.category===activeCategory)&&(`${c.name} ${c.tagline} ${c.personality}`.toLowerCase().includes(q)));$('#character-grid').innerHTML=list.length?list.map(c=>`<article class="character-card"><button class="card-open" data-character="${c.id}" style="all:unset;display:block;width:100%;cursor:pointer">${portrait(c)}<div class="card-body"><span class="tag">${escapeHtml(c.category)}</span><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.tagline)}</p><button class="primary full" data-character="${c.id}">Chat</button></div></button></article>`).join(''):`<div class="empty">No characters found. Try another search or create one.</div>`}
function openChat(id){const c=state.characters.find(x=>x.id===id);if(!c)return;activeId=id;if(!state.chats[id])state.chats[id]=[{role:'assistant',content:c.greeting||`Hi! I'm ${c.name}.`}];save();$('#chat-character-card').innerHTML=`<div class="chat-character">${portrait(c)}<h2>${escapeHtml(c.name)}</h2><p>${escapeHtml(c.tagline)}</p><span class="tag">${escapeHtml(c.category)}</span></div>`;$('#chat-header').textContent=c.name;renderMessages();showView('chat');setTimeout(()=>$('#message-input').focus(),50)}
function renderMessages(){const box=$('#messages');box.innerHTML=(state.chats[activeId]||[]).map(m=>`<div class="message ${m.role==='user'?'user':'ai'}"><span>${escapeHtml(m.content)}</span><span class="meta">${m.role==='user'?'You':state.characters.find(c=>c.id===activeId)?.name||'AI'}</span></div>`).join('');box.scrollTop=box.scrollHeight}
function demoReply(c,msg){const lower=msg.toLowerCase();if(lower.includes('hello')||lower.includes('hi'))return c.greeting||`Hey! I'm ${c.name}.`;if(lower.includes('who are you'))return `I'm ${c.name}. ${c.backstory}`;if(lower.includes('help'))return `Absolutely. Tell me what you need and I'll do my best to help—in my own ${c.style||'style'}.`;const starters=[`That is interesting. What makes you think about it that way?`,`Okay, I'm listening. Tell me more!`,`I like where this is going. If I were answering as myself, I'd say: ${msg} sounds like the start of a story.`,`Hmm... ${msg}. You've got my attention. What happens next?`];return starters[Math.floor(Math.random()*starters.length)]}
async function generateReply(c,messages){const url=(state.settings.apiUrl||DEFAULT_BACKEND).trim();if(url){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({character:{id:c.id,name:c.name,personality:c.personality,backstory:c.backstory,style:c.style},messages})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();if(data.reply)return data.reply;throw new Error('No reply returned')}catch(e){console.warn('AI backend failed',e);if(!state.settings.demo)throw e}}if(state.settings.demo)return demoReply(c,messages.at(-1)?.content||'');throw new Error('AI backend unavailable. Check the backend deployment or Settings.')}
function speak(text,c){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=c.voice==='male'?.82:c.voice==='female'?1.12:1;u.onstart=()=>$('#chat-character-card .portrait')?.classList.add('speaking');u.onend=u.onerror=()=>$('#chat-character-card .portrait')?.classList.remove('speaking');speechSynthesis.speak(u)}
async function sendMessage(text){const clean=text.trim();if(!clean||!activeId)return;const c=state.characters.find(x=>x.id===activeId);const chat=state.chats[activeId]||[];chat.push({role:'user',content:clean});state.chats[activeId]=chat;save();renderMessages();$('#message-input').value='';$('#typing').classList.remove('hidden');try{const reply=await generateReply(c,chat.slice(-18));chat.push({role:'assistant',content:reply});save();renderMessages();speak(reply,c)}catch(e){chat.push({role:'assistant',content:`⚠️ ${e.message}`});save();renderMessages()}finally{$('#typing').classList.add('hidden')}}
function createCharacter(form){const fd=new FormData(form);const c={id:`custom-${Date.now()}`,name:fd.get('name').trim(),avatar:fd.get('avatar').trim(),tagline:fd.get('tagline').trim()||'A new AI character.',category:fd.get('category'),personality:fd.get('personality').trim(),backstory:fd.get('backstory').trim(),style:fd.get('style').trim()||'Natural and conversational.',voice:fd.get('voice'),greeting:fd.get('greeting').trim()||`Hey! I'm ${fd.get('name').trim()}. Nice to meet you!`};state.characters.unshift(c);save();form.reset();$('#avatar-preview').innerHTML='<span>?</span>';renderCharacters();openChat(c.id)}
function loadSettings(){$('#api-url').value=state.settings.apiUrl||DEFAULT_BACKEND;$('#demo-mode').checked=state.settings.demo===true}
function deleteActive(){if(!activeId)return;const c=state.characters.find(x=>x.id===activeId);if(!c||!c.id.startsWith('custom-'))return alert('Built-in characters cannot be deleted.');if(!confirm(`Delete ${c.name}?`))return;state.characters=state.characters.filter(x=>x.id!==activeId);delete state.chats[activeId];save();activeId=null;renderCharacters();showView('discover')}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]')?.dataset.view;if(view){showView(view);if(view==='settings')loadSettings();return}const id=e.target.closest('[data-character]')?.dataset.character;if(id){e.preventDefault();openChat(id);return}const cat=e.target.closest('[data-category]')?.dataset.category;if(cat){activeCategory=cat;renderCharacters();return}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='settings'){showView('settings');loadSettings()}if(action==='clear-chat'&&activeId){const c=state.characters.find(x=>x.id===activeId);state.chats[activeId]=[{role:'assistant',content:c.greeting||`Hi! I'm ${c.name}.`}];save();renderMessages()}if(action==='delete-character')deleteActive();if(action==='stop-speaking')speechSynthesis.cancel();if(action==='save-settings'){state.settings.apiUrl=$('#api-url').value.trim()||DEFAULT_BACKEND;state.settings.demo=$('#demo-mode').checked;save();alert('Settings saved.')}});
$('#character-search').addEventListener('input',renderCharacters);
$('#character-form').addEventListener('submit',e=>{e.preventDefault();createCharacter(e.currentTarget)});
$('#character-form').addEventListener('input',e=>{if(e.target.name==='avatar'){const url=e.target.value.trim();$('#avatar-preview').innerHTML=url?`<img src="${escapeHtml(url)}" alt="preview" onerror="this.parentElement.innerHTML='<span>?</span>'">`:'<span>?</span>'}});
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#message-input').value)});
$('#message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chat-form').requestSubmit()}});
renderCharacters();